# Generated by Django 3.1.5 on 2021-01-15 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('d_ID', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('d_name', models.CharField(default=0, max_length=20)),
                ('d_phone', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('m_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('m_name', models.CharField(default=0, max_length=20)),
                ('m_inventory', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('m_price', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('m_date', models.DateField(default=datetime.datetime(2021, 1, 15, 16, 2, 55, 928231))),
                ('m_hcost', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('m_estsupply', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('m_estdemand', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_name', models.CharField(default=0, max_length=20)),
                ('p_price', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('p_inventory', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('p_cost', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('p_hcost', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('p_estsupply', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('p_estdemand', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('Period', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('Retention', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('Survival', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('Active_Customers', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('Active_Periods', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('s_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('s_name', models.CharField(default=0, max_length=20)),
                ('s_phone', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('m_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.material')),
                ('p_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('o_amount', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('o_price', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('o_profit', models.DecimalField(decimal_places=0, default=100, max_digits=8)),
                ('o_date', models.DateField(default=datetime.date.today)),
                ('d_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.dealer')),
                ('p_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('o_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('p_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
